using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MaJiang;
using MaJiang.DataConstruct.Relic;
using MaJiang.DataConstruct.XiaoChouPai;
using MaJiang.DataConstruct.Character;


namespace DemonicMahjongArchipelago
{

    internal class ItemNames
    {
        public static class Constants
        {
			public const int ITEM_OFFSET = 4624000;
            public const int CHAR_OFFSET = ITEM_OFFSET;
            public const int FIGURINE_OFFSET = ITEM_OFFSET + 1000;
            public const int RELIC_OFFSET = ITEM_OFFSET + 2000;
        }

        public static Dictionary<CharacterID, string> CharacterNames = new Dictionary<CharacterID, string>
        {
			{CharacterID.TanChiJiangShi, "Chowbo"},
			{CharacterID.TanCaiJiangShi, "Coina"},
			{CharacterID.BuRangPengJiangShi, "Pungpon"},
			{CharacterID.ZiBiNvGui, "Seeping Cici"},
			{CharacterID.YuanNianNvGui, "Wailing Ling"},
			{CharacterID.XiongENvGui, "Scary Susy"},
			{CharacterID.NiuTou, "Abang Ox-head"},
			{CharacterID.MaMian, "Aqi Horse-face"},
			{CharacterID.HeiWuChang, "Black Impermanence"},
			{CharacterID.BaiWuChang, "White Impermanence"},
			{CharacterID.DiTing, "Diting"},
			{CharacterID.NiuTouMaMian, "Abang Ox-head & Aqi Horse-face"},
			{CharacterID.HeiBaiWuChang, "Black & White Impermanence"},
			{CharacterID.MengPo, "Meng Po"},
			{CharacterID.QinGuangWang, "King Qinguang"},
			{CharacterID.YanLuoWang, "King Yama"},
			{CharacterID.DiZangWangPuSa, "Ksitigarbha"},
			{CharacterID.ChaChaSi, "Inquiry Judge Lu"},
			{CharacterID.FaESi, "Sin Judge Zhong"},
			{CharacterID.HenDuJiangShi, "ToxTox"},
			{CharacterID.JiKeNvGui, "Craving Kae"},
			//{CharacterID.LouCha, "AAAA"},									// Not Implemented?
			{CharacterID.ShangShanSi, "Virtue Judge Wei"},
			{CharacterID.YinLvSi, "Lawkeeper Cui"},
			//{CharacterID.DiZangWangPuSa02, ""},								// Not Implemented?
			{CharacterID.GuiXinNiangXu, "Wither"},
			{CharacterID.GuiXinNiangKui, "Marionette"},
			{CharacterID.GuiXinNiangYan, "Nightmare"},
			{CharacterID.GuiXinNiangMei, "Temptress"},
			{CharacterID.RiYouShen, "Day Warden"},
			{CharacterID.YeYouShen, "Night Warden"},
			{CharacterID.TaiShanWang, "King Taishan"},
			//{CharacterID.HenDuJiangShi_Beiginner, ""},
			//{CharacterID.DiTing_Beiginner, ""},
			//{CharacterID.YuanNianNvGui_Beiginner, ""},
			//{CharacterID.ChaChaSi_Beiginner, ""},
		};

		public static List<CharacterID> CharacterIds = CharacterNames.Keys.ToList();

        public static Dictionary<XiaoChou, string> FigurineNames = new Dictionary<XiaoChou, string>
        {
			{XiaoChou.BaiLong, "White Dragon"},
			{XiaoChou.BaiMianXiaoGui, "Pale Imp"},
			{XiaoChou.JuCaiHe, "Thriving Crane"},
			{XiaoChou.BaiZe, "Bai Ze"},
			{XiaoChou.Bao4ShiXiaoYao, "Gorging Puck"},
			{XiaoChou.BaoShiWaWa, "Gem Doll"},
			{XiaoChou.BaoNuXiaoYao, "Enraged Puck"},
			{XiaoChou.BaoShiGuai, "Gorging Monster"},
			{XiaoChou.BaoShiXiaoYao, "Gem Puck"},
			{XiaoChou.BaoShiHuDie, "Gem Butterfly"},
			{XiaoChou.BaoShiRenYong, "Gem Effigy"},
			{XiaoChou.HuPengGui, "Party Ghost"},
			{XiaoChou.XiaoXiaoShu, "Tiny Rat"},
			{XiaoChou.BiFang, "Bi Fang"},
			{XiaoChou.BingFeng, "Bing Feng"},
			{XiaoChou.BiYiNiao, "Lovebirds"},
			{XiaoChou.XueShuXiao, "Numerical Owl"},
			{XiaoChou.CangGuXia, "Skull Casket"},
			{XiaoChou.ChanDingGuiChai, "Zen Bailiff"},
			{XiaoChou.ChanZuiNiu, "Fruit Bull"},
			{XiaoChou.PuTiNiu, "Grape Bull"},
			{XiaoChou.ChuFeng, "Baby Phoenix"},
			{XiaoChou.DaDaXiang, "Jumbo"},
			{XiaoChou.DangKang, "Dang Kang"},
			{XiaoChou.CiTuan, "Spiky"},
			{XiaoChou.DuFeng, "Toxic Wind"},
			{XiaoChou.YuanYang, "Twin Ducks"},
			{XiaoChou.DuYuanSu, "Toxin"},
			{XiaoChou.FangShengChi, "Release Pool"},
			{XiaoChou.FeiCuiDiXian, "Jade Deity"},
			{XiaoChou.FengZhiGuan, "Wind Jar"},
			{XiaoChou.FenShenPen, "Clone Basin"},
			{XiaoChou.FuDaiGuai, "Lucky Bag"},
			{XiaoChou.FuGuiZhu, "Fortune Pig"},
			{XiaoChou.GangKaiHuXian, "Kong Vixen"},
			{XiaoChou.KeBanWaWa, "Stiff Doll"},
			{XiaoChou.GuHu, "Skull Fox"},
			{XiaoChou.GuHun, "Lonely Ghost"},
			{XiaoChou.GuiHu, "Demon Fox"},
			{XiaoChou.GuiShuai, "Demon Lord"},
			{XiaoChou.GuiYiWaWa, "Unison Doll"},
			{XiaoChou.HeiYuGui, "Jet Turtle"},
			{XiaoChou.HongBaoNiu, "Ruby Bull"},
			{XiaoChou.HongKuLou, "Red Skeleton"},
			{XiaoChou.HongLong, "Red Dragon"},
			{XiaoChou.HongLongYuXi, "Jade Seal"},
			{XiaoChou.HuaGuanNiu, "Wreath Bull"},
			{XiaoChou.HuanFengHuXian, "Wind Vixen"},
			{XiaoChou.HuangJinDan, "Gold Egg"},
			{XiaoChou.WanLiHe, "Loaded Crane"},
			{XiaoChou.HuangLuanXiaoYao, "Rattled Puck"},
			{XiaoChou.DieDieXiaoYao, "Stacked Puck"},
			{XiaoChou.HuanLi, "Fantasy"},
			{XiaoChou.HuaXinWaWa, "Suitor Doll"},
			{XiaoChou.DanZhongDan, "Nesting Egg"},
			{XiaoChou.HuXianXueTu, "Vixen Pupil"},
			{XiaoChou.JiEXiaoYao, "Starved Puck"},
			{XiaoChou.JinBaoMao, "Treasure Cat"},
			{XiaoChou.JinChan, "Gold Toad"},
			{XiaoChou.JinGouDiao, "Gold Hook"},
			{XiaoChou.JingWei, "Jing Wei"},
			{XiaoChou.JingYaXiaoYao, "Aghast Puck"},
			{XiaoChou.JinJiGui, "Combat Turtle"},
			{XiaoChou.JiuWeiHu, "Nine Tail Fox"},
			{XiaoChou.JiXiangTu, "Lucky Rabbit"},
			{XiaoChou.JiXiangXiaoMa, "Lucky Horse"},
			{XiaoChou.JuDuDiXian, "Toxic Deity"},
			{XiaoChou.KongChaoRenYong, "Absent Effigy"},
			{XiaoChou.KuaiLeXiaoYao, "Gleeful Puck"},
			{XiaoChou.KuLouXiaoYao, "Bony Puck"},
			{XiaoChou.KuoRongDan, "Nesting Egg 2"},
			{XiaoChou.LanYuDiXian, "Azure Deity"},
			{XiaoChou.LaoYueHou, "Moon Monkey"},
			{XiaoChou.LaZhuHou, "Wax Monkey"},
			{XiaoChou.LaZhuRenYong, "Wax Effigy"},
			{XiaoChou.LaZhuWaWa, "Wax Doll"},
			{XiaoChou.LaZhuXiaoYao, "Wax Puck"},
			{XiaoChou.LianHuaBao, "Lotus Bud"},
			{XiaoChou.LongWeiHuXian, "Dragon Vixen"},
			{XiaoChou.LvLong, "Green Dragon"},
			{XiaoChou.MaGu, "Horse Skull"},
			{XiaoChou.MaoShiGui, "Rash Ghost"},
			{XiaoChou.MengLi, "Dream"},
			{XiaoChou.MiLi, "Illusion"},
			{XiaoChou.MinGanXiaoGui, "Sensitive Imp"},
			{XiaoChou.MingXiangHou, "Sage Monkey"},
			{XiaoChou.MuQiangGui, "Power Ghost"},
			{XiaoChou.DianPaoRenYong, "Sparky Effigy"},
			{XiaoChou.PiLiRenYong, "Stormy Effigy"},
			{XiaoChou.PingFanRenYong, "Average Effigy"},
			{XiaoChou.PingFanWaWa, "Average Doll"},
			{XiaoChou.PingFanXiaoYao, "Average Puck"},
			{XiaoChou.PiXiu, "Pi Xiu"},
			{XiaoChou.XiangYuShu, "Big & Small"},
			{XiaoChou.QiLin, "Qi Lin"},
			{XiaoChou.QingLuan, "Qing Luan"},
			{XiaoChou.CaiDan, "Easter Egg"},
			{XiaoChou.QiTongWaWa, "Dot Doll"},
			{XiaoChou.QiuSuoWaWa, "Bamboo Doll"},
			{XiaoChou.RongHuaZhu, "Glory Pig"},
			{XiaoChou.LianHuaShiZhe, "Lotus Acolyte"},
			{XiaoChou.SanCaiYuLong, "Tricolor Dragon"},
			{XiaoChou.SanTouQuan, "Cerberus"},
			{XiaoChou.SanXiongDi, "The Trio"},
			{XiaoChou.ShanDianWaWa, "Lightning Doll"},
			{XiaoChou.ShengCaiGuiChai, "Gain Bailiff"},
			{XiaoChou.ShenMiDan, "Mystery Egg"},
			{XiaoChou.ShiHunWaWa, "Stricken Doll"},
			{XiaoChou.ChanDingHou, "Zen Monkey"},
			{XiaoChou.TunTun, "Chompers"},
			{XiaoChou.ShuangYuShe, "Twin Snake"},
			{XiaoChou.GaoDianNiu, "Pastry Bull"},
			{XiaoChou.ShunXinMao, "Gracious Cat"},
			{XiaoChou.ShuShengWaWa, "Scholar Doll"},
			{XiaoChou.SongLanNiu, "Woad Bull"},
			{XiaoChou.SuanLingHuXian, "Math Vixen"},
			{XiaoChou.SuoTouGui, "Hiding Turtle"},
			{XiaoChou.WanFuWaWa, "Character Doll"},
			{XiaoChou.TanChiRenYong, "Munchy Effigy"},
			{XiaoChou.TaoTie, "Gluttony"},
			{XiaoChou.TianGou, "Sky Dog"},
			{XiaoChou.TieTieJinLi, "Snuggling Koi"},
			{XiaoChou.XiaoShunWaWa, "Filial Doll"},
			{XiaoChou.JiShiGuai, "Rite Monster"},
			{XiaoChou.TunShiGuai, "Gulp Monster"},
			{XiaoChou.TuZhiBo, "Rabbit Bowl"},
			{XiaoChou.WeiFeng, "Breeze"},
			{XiaoChou.WeiSuoXiaoYao, "Snaky Puck"},
			{XiaoChou.WuSeShenNiu, "Divine Bull"},
			{XiaoChou.DanShenGou, "Single Dog"},
			{XiaoChou.DuJiaGui, "Viper Turtle"},
			{XiaoChou.XiaoShiYe, "Master Owlet"},
			{XiaoChou.XuanGui, "Xuan Gui"},
			{XiaoChou.XueJian, "Bloody Cocoon"},
			{XiaoChou.XieZhi, "Xie Zhi"},
			{XiaoChou.YinBanGui, "Lure Ghost"},
			{XiaoChou.YinLuGuiChai, "Guide Bailiff"},
			{XiaoChou.YiNuXiaoGui, "Irritable Imp"},
			{XiaoChou.YiTongHuXian, "Askew Vixen"},
			{XiaoChou.YongSuXiaoYao, "Vulgar Puck"},
			{XiaoChou.YuTu, "Jade Hare"},
			{XiaoChou.YeGui, "Savage Ghost"},
			{XiaoChou.XiangJiaoNiu, "Banana Bull"},
			{XiaoChou.ZhaoCaiMao, "Wealth Cat"},
			{XiaoChou.ZhongYongTu, "Mean Rabbit"},
			{XiaoChou.ZuiHou, "Drunk Monkey"},
			{XiaoChou.ZuZhuXiaoYao, "Cursed Puck"},
			{XiaoChou.MinNiu, "Sensitive Ox"},
			{XiaoChou.YouHu, "Baby Fox"},
			{XiaoChou.FengShengHu, "Breezy Fox"},
			{XiaoChou.DuXingXiao, "Lone Owl"},
			{XiaoChou.ShiHunDie, "Soul Butterfly"},
			{XiaoChou.DieMaoMao, "Cat Pile"},
			{XiaoChou.HuaXinRenYong, "Flirty Effigy"},
			{XiaoChou.Lei, "Typical"},
			{XiaoChou.Gui3Hun, "Ghost Soul"},
			{XiaoChou.GuiHun, "Turtle Soul"},
			{XiaoChou.HeHun, "Crane Soul"},
			{XiaoChou.SheHun, "Snake Soul"},
			{XiaoChou.BaGe, "Pug"},
			{XiaoChou.YiWangWaWa, "Forgetful Doll"},
			{XiaoChou.LuShu, "Lu Shu"},
			{XiaoChou.BiJianShou, "Twin Beast"},
			{XiaoChou.SheDe, "Farewell"},
			{XiaoChou.ShiHunXiaoYao, "Soul Puck"},
			{XiaoChou.WenYao, "Wen Yao"},
			{XiaoChou.JiuSeLu, "Radiant Deer"},
			{XiaoChou.ShuangShuang, "Duplet"},
			{XiaoChou.FengHuangDan, "Phoenix Egg"},
			{XiaoChou.PuMan, "Piggy Pouch"},
			{XiaoChou.ChiQingXiaoGui, "Amorous Imp"},
			{XiaoChou.ChiWen, "Chiwen"},
			{XiaoChou.QiongQi, "Qiongqi"},
			{XiaoChou.BaiLang, "White Wolf"},
			{XiaoChou.JieKong, "Void"},
			{XiaoChou.KongChaoWaWa, "Absent Doll"},
			{XiaoChou.KongChaoXiaoYao, "Absent Puck"},
			{XiaoChou.ChiTun, "Chiru"},
			{XiaoChou.SanCaiHe, "Tycoon Crane"},
			{XiaoChou.ChuanXinGuiChai, "Courier Bailiff"},
			{XiaoChou.ChanZuiWaWa, "Glutton Doll"},
			{XiaoChou.JingTanGuai, "Scrub Monster"},
			{XiaoChou.NingHunDie, "Aura Butterfly"},
			{XiaoChou.QingShe, "Green Snake"},
			{XiaoChou.QiongDie, "Jade Butterfly"},
			{XiaoChou.ChiLianShe, "Crimsonlash"},
			{XiaoChou.SanLingShe, "Tri-Snake"},
			{XiaoChou.ShouShenShe, "Bamboo Snake"},
			{XiaoChou.TaoWu, "Tao Wu"},
			{XiaoChou.YvNiu, "Jade Bull"},
			{XiaoChou.ShiXinGui, "Soulless Ghost"},
			{XiaoChou.WeiLiao, "Epilogue"},
			{XiaoChou.HuaXiaoGu, "Bloomskull"},
			{XiaoChou.KongXinDan, "Hollow Egg"},
			{XiaoChou.YaoQuan, "Gleamhound"},
			{XiaoChou.YeMao, "Nightcat"},
			{XiaoChou.MaDaoZhang, "Horse Priest"},
			{XiaoChou.MuOuNiu, "Puppet Ox"},
			{XiaoChou.YinMengDie, "Dreamlure"},
			{XiaoChou.ZhuanYiWaWa, "Solemn Doll"},
			{XiaoChou.FanYin, "Dharma's Echo"},
			{XiaoChou.LiangYiGui, "Duality Turtle"},
			{XiaoChou.LingDan, "Spirit Egg"},
			{XiaoChou.QianXunWaWa, "Humble Doll"},
			{XiaoChou.QianXunXiaoYao, "Humble Puck"},
			{XiaoChou.TanCaiHe, "Avarice Crane"},
			{XiaoChou.XiangLiu, "Xiangliu"},
			{XiaoChou.QianKunHe, "Fortune Crane"},
			{XiaoChou.HunDun, "Hundun"},
			{XiaoChou.CaiYi, "Prismwing Bat"},
			{XiaoChou.CangJiao, "Sniffhorn"},
			{XiaoChou.LingGuTa, "Soul Spire"},
			{XiaoChou.LiuErMiHou, "The Macaque"},
			{XiaoChou.RangJiao, "Wagglehorn"},
			{XiaoChou.YinYangYu, "Lunasol Scale"},
			{XiaoChou.ZhenYue, "Tombweight"},
			{XiaoChou.LuWu, "Lu Wu"},
			{XiaoChou.GuiMianWaWa, "Ghostface Doll"},
			{XiaoChou.ShiMengDie, "Dreambite"},
			{XiaoChou.YouYou, "Youyou"},
			{XiaoChou.GuiMianXiaoYao, "Ghostface Puck"},
			{XiaoChou.SanCaiNiu, "Winterbloom"},
		};

        public static List<XiaoChou> FigurineIds = FigurineNames.Keys.ToList();

        public static Dictionary<RelicId, string> RelicNames = new Dictionary<RelicId, string>
        {
			{RelicId.BaoPing, "Antique Flask"},
			{RelicId.BaoShiBiShou, "Gemstone Dagger"},
			{RelicId.BuXiangGongTai, "Ominous Altar"},
			{RelicId.ChangMingSuo, "Longevity Lock"},
			{RelicId.ChuXuGuan, "Piggy Bank"},
			{RelicId.DiaoHuaShiHe, "Carved Food Box"},
			{RelicId.DiFuTeng, "Demonic Vine"},
			{RelicId.DiYuBaoXiang, "Whisper Chest"},
			{RelicId.EGuiFan, "Devil Banner"},
			{RelicId.FaChi, "Ritual Ruler"},
			{RelicId.FaYin, "Ritual Seal"},
			{RelicId.FengLing, "Wind Token"},
			{RelicId.FengXianBaoXiang, "Devotion Chest"},
			{RelicId.FuChen, "Horsetail Whisk"},
			{RelicId.GuaiYiGongTai, "Grim Altar"},
			{RelicId.GuiCheng, "Ghost Scale"},
			{RelicId.GuiMianJu, "Evil Mask"},
			{RelicId.HunYuanJing, "Chaotic Mirror"},
			{RelicId.JiMaoDan, "Feather Duster"},
			{RelicId.JinFanWan, "Gold Bowl"},
			{RelicId.JinGangChu, "Vajra"},
			{RelicId.JinHe, "Brocade Box"},
			{RelicId.JinHuLu, "Golden Gourd"},
			{RelicId.JinRuYi, "Gold Ruyi"},
			{RelicId.JinZhu, "Gold Bead"},
			{RelicId.JiXiangJie, "Auspicious Knot"},
			{RelicId.JuBaoPen, "Cornucopia"},
			{RelicId.KongBuLaZhu, "Horror Candle"},
			{RelicId.KongQueLing, "Peacock Feather"},
			{RelicId.KuLouZhuTai, "Skull Candle"},
			{RelicId.LianDeng, "Lotus Candle"},
			{RelicId.LianTai, "Lotus Stand"},
			{RelicId.LongHunFan, "Dragon Banner"},
			{RelicId.LongLing, "Dragon Token"},
			{RelicId.MiHunXiang, "Alluring Censer"},
			{RelicId.MoDaoShi, "Grindstone"},
			{RelicId.PingAnKou, "Lucky Jade"},
			{RelicId.PoWan, "Broken Bowl"},
			{RelicId.QianKunQuan, "Cosmic Ring"},
			{RelicId.KeLing, "Triplet Token"},
			{RelicId.QianPai, "Money Token"},
			{RelicId.QingLingGuan, "Soul Crown"},
			{RelicId.QingMingJian, "Qingming Sword"},
			{RelicId.QiXingDeng, "Nova Candelabra"},
			{RelicId.QueYuePei, "Crescent Jade"},
			{RelicId.ShengXiuDingZi, "Rusty Nail"},
			{RelicId.ShouKao, "Handcuffs"},
			{RelicId.ShuangRenJian, "Double Edged"},
			{RelicId.ShuQi, "Rat Stone"},
			{RelicId.SuoLing, "Bamboo Token"},
			{RelicId.SuoQi, "Bamboo Stone"},
			{RelicId.TaiSui, "Taisui"},
			{RelicId.TaoMuJian, "Peachblade"},
			{RelicId.TianDeng, "Sky Lantern"},
			{RelicId.TieFanWan, "Iron Bowl"},
			{RelicId.TongLing, "Dot Token"},
			{RelicId.TongQi, "Dot Stone"},
			{RelicId.TuQi, "Rabbit Stone"},
			{RelicId.WanLing, "Character Token"},
			{RelicId.WanQi, "Character Stone"},
			{RelicId.WuGuWaWa, "Voodoo Doll"},
			{RelicId.XiangQi, "Elephant Stone"},
			{RelicId.YaoQianShu, "Money Tree"},
			{RelicId.YeMingZhu, "Luminous Pearl"},
			{RelicId.YinSiBi, "Shade Coin"},
			{RelicId.YouAnFan, "Dark Banner"},
			{RelicId.YuFo, "Jade Buddha"},
			{RelicId.YuHuLu, "Jade Gourd"},
			{RelicId.YuRuYi, "Jade Ruyi"},
			{RelicId.ZhaoHunFan, "Conjure Banner"},
			{RelicId.ZhenZhi, "Paperweight"},
			{RelicId.ZhiRen, "Paper Doll"},
			{RelicId.ZhuQueYin, "Vermilion Seal"},
			{RelicId.ZhuanJingTong, "Prayer Wheel"},
			{RelicId.ZhuCanLan, "Bamboo Basket"},
			{RelicId.ZiQi, "Honor Stone"},
			{RelicId.ZouMaDeng, "Horse Lamp"},
			{RelicId.ZuZhouBaoXiang, "Cursed Chest"},
			{RelicId.AnYingZhen, "Venom Dagger"},
			{RelicId.TongShunZhu, "Order Beads"},
			{RelicId.ShengTianGun, "Ascension Rod"},
			{RelicId.BuYunLv, "Soaring Shoes"},
			{RelicId.JiuHuanXiZhang, "Khakkara"},
			{RelicId.BaiFaLuo, "White Conch"},
			{RelicId.MaLiangShenBi, "Magic Brush"},
			{RelicId.ZhenHunLing, "Soul Bell"},
			{RelicId.JuDuGongTai, "Toxic Altar"},
			{RelicId.MiWuGongTai, "Mist Altar"},
			{RelicId.DiYuGongTai, "Hushed Altar"},
			{RelicId.XiShengGongTai, "Sacrifice Altar"},
			{RelicId.ShunLing, "Sequence Token"},
			{RelicId.XiangLing, "Elephant Token"},
			{RelicId.ShuLing, "Rat Token"},
			{RelicId.TuLing, "Rabbit Token"},
			{RelicId.ShiNianDao, "Psyche Blade"},
			{RelicId.HongYingQiang, "Red Tassel Spear"},
			{RelicId.YuWan, "Jade Bowl"},
			{RelicId.BiShan, "Mountain Stand"},
			{RelicId.ZhouDuRen, "Cursed Blade"},
			{RelicId.DiYuBiShou, "Hushed Dagger"},
			{RelicId.ChiNianBaoXiang, "Fool's Chest"},
			{RelicId.FengLingZhu, "Wind Orb"},
			{RelicId.ZhuNengShi, "Value Stone"},
			{RelicId.LongZhu, "Dragon Orb"},
			{RelicId.LianHuaFan, "Lotus Banner"},
			{RelicId.LianHuaGuan, "Lotus Crown"},
			{RelicId.LaoYueLan, "Lunar Basket"},
			{RelicId.CanYuePan, "Crescent Plate"},
			{RelicId.ManYue, "Full Moon Lamp"},
		};

        public static List<RelicId> RelicIds = RelicNames.Keys.ToList();
    }
}
