using MaJiang.DataConstruct.MaJiang;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DemonicMahjongArchipelago
{
    internal class LocationNames
    {

        public const int LOCATION_OFFSET = ItemNames.ITEM_OFFSET + 100000;
        public const int YAKU_OFFSET = LOCATION_OFFSET;
        public const int CHARACTER_OFFSET = LOCATION_OFFSET + 1000;
        public const int DIFFICULTY_OFFSET = LOCATION_OFFSET + 2000;
        public const int ACHIEVEMENT_OFFSET = LOCATION_OFFSET + 3000;

        public static Dictionary<FanZhong, string> YakuNames = new Dictionary<FanZhong, string>
        {
			{FanZhong.AnGang, "Concealed Kong"},
            {FanZhong.BianZhang, "Edge Wait"},
            {FanZhong.BuQiuRen, "Fully Concealed"},
            {FanZhong.DaSanYuan, "Big Three Dragons"},
            {FanZhong.DaSiXi, "Big Four Winds"},
            {FanZhong.DaYuWu, "Upper Five"},
            {FanZhong.DuanYao, "All Simples"},
            {FanZhong.FengKe, "Wind Pung"},
            {FanZhong.GangShangKaiHua, "Out with Replacement Tile"},
            {FanZhong.GuYiChangSheZhen, "Olden·Snake Force"},
            {FanZhong.GuYiGuiJiaZhen, "Olden·Turtle Force"},
            {FanZhong.GuYiHeiYiSe, "Olden·Black Only"},
            {FanZhong.GuYiHeYiZhen, "Olden·Crane Force"},
            {FanZhong.GuYiHongKongQue, "Olden·Red Peacock"},
            {FanZhong.GuYiHongYiDian, "Olden·Red Center"},
            {FanZhong.GuYiJinJiDuLi, "Olden·Golden Rooster"},
            {FanZhong.GuYiQiShaZhen, "Olden·Seven Stars"},
            {FanZhong.GuYiYuanZhouLv, "Olden·Pi"},
            {FanZhong.HaiDiLaoYue, "Last Tile Claim"},
            {FanZhong.HuaLong, "Mixed Straight"},
            {FanZhong.HunYaoJiu, "All Terminals & Honors"},
            {FanZhong.HunYiSe, "Half Flush"},
            {FanZhong.JianKe, "Dragon Pung"},
            {FanZhong.JinGouDiao, "All Exposed"},
            {FanZhong.JiuLianBaoDeng, "Nine Gates"},
            {FanZhong.KanZhang, "Closed Wait"},
            {FanZhong.LaoShaoFu, "Two Terminal Chows"},
            {FanZhong.LianLiu, "Short Straight"},
            {FanZhong.LianQiDui, "Seven Shifted Pairs"},
            {FanZhong.LvYiSe, "All Green"},
            {FanZhong.MenQianQing, "Concealed Hand"},
            {FanZhong.MingGang, "Melded  Kong"},
            {FanZhong.PengPengHu, "All Pungs"},
            {FanZhong.PingHu, "All Chows"},
            {FanZhong.QiDui, "Seven Pairs"},
            {FanZhong.QingLong, "Pure Straight"},
            {FanZhong.QingYaoJiu, "Pure Terminals"},
            {FanZhong.QingYiSe, "Full Flush"},
            {FanZhong.QuanDa, "Upper Tiles "},
            {FanZhong.QuanDaiWu, "All Fives"},
            {FanZhong.QuanDaiYao, "Outside Hand"},
            {FanZhong.QuanGuiYi, "Perfect Uniformity"},
            {FanZhong.QuanQiuRen, "Melded Hand"},
            {FanZhong.QuanShuangKe, "All Even Pungs"},
            {FanZhong.QuanXiao, "Lower Tiles"},
            {FanZhong.QuanZhong, "Middle Tiles"},
            {FanZhong.QueYiMen, "One Voided Suit"},
            {FanZhong.SanAnKe, "Three Concealed Pungs"},
            {FanZhong.SanFengKe, "Big Three Winds"},
            {FanZhong.SanGang, "Three Kongs"},
            {FanZhong.SanSeSanBuGao, "Mixed Shifted Chows"},
            {FanZhong.SanSeSanJieGao, "Mixed Shifted Pungs"},
            {FanZhong.SanSeSanTongShun, "Mixed Triple Chow"},
            {FanZhong.SanSeShuangLongHui, "Mixed Terminal Chows"},
            {FanZhong.SanTongKe, "Triple Pung"},
            {FanZhong.ShiSanYao, "Thirteen Orphans"},
            {FanZhong.ShuangAnGang, "Two Concealed Kongs"},
            {FanZhong.ShuangAnKe, "Two Concealed Pungs"},
            {FanZhong.ShuangJianKe, "Two Dragon Pungs"},
            {FanZhong.ShuangMingGang, "Two Melded Kongs"},
            {FanZhong.ShuangTongKe, "Double Pung"},
            {FanZhong.SiAnKe, "Four Concealed Pungs"},
            {FanZhong.SiGang, "Four Kongs"},
            {FanZhong.SiGuiYi, "Tile Hog"},
            {FanZhong.TuiBuDao, "Reversible Tiles"},
            {FanZhong.WuFanHu, "Emptiness"},
            {FanZhong.WuMenQi, "All Types"},
            {FanZhong.WuZi, "No Honors"},
            {FanZhong.XiaoSanYuan, "Little Three Dragons"},
            {FanZhong.XiaoSiXi, "Little Four Winds"},
            {FanZhong.XiaoYuWu, "Lower Five"},
            {FanZhong.XiXiangFeng, "Mixed Double Chow"},
            {FanZhong.YiBanGao, "Pure Double Chow"},
            {FanZhong.YiSeSanBuGao, "Pure Shifted Chows"},
            {FanZhong.YiSeSanJieGao, "Three Shifted Pungs"},
            {FanZhong.YiSeSanTongShun, "Pure Triple Chow"},
            {FanZhong.YiSeShuangLongHui, "Pure Terminal Chows"},
            {FanZhong.YiSeSiBuGao, "Four Shifted Chows"},
            {FanZhong.YiSeSiJieGao, "Four Shifted Pungs"},
            {FanZhong.YiSeSiTongShun, "Quadruple Chow"},
            {FanZhong.ZiYiSe, "All Honors"},
            {FanZhong.QiXingBuKao, "Greater Honors and Knitted Tiles"},
            {FanZhong.QuanBuKao, "Lesser Honors and Knitted Tiles"},
            {FanZhong.ZuHeLong, "Knitted Straight"},
            {FanZhong.YaoJiuke, "Pung of Terminals or Honors"},
            {FanZhong.GuYiAnLong, "Olden·Hidden Dragon"},
            {FanZhong.QuanShuangDui, "All Even Pairs"},
            {FanZhong.SanYuanGuiYi, "Triple Dragons Unite"},
            {FanZhong.GuYiYiLongZhuoWuKui, "Olden·Dragon 5 Honors"},
            {FanZhong.GuYiWuXinTongGuan, "Olden·Five Hearts"},
            {FanZhong.GuYiDuDiaoHanJiangXue, "Olden·Solitary White"},
            {FanZhong.GuYiWuFuLinMen, "Olden·Five Blessings"},
            {FanZhong.TianHu, "Heavenly Hand"},
            {FanZhong.DiHu, "Earthly Hand"},
            {FanZhong.GuYiHuaTianYueDi, "Olden·Midnight Bloom"},
            {FanZhong.GuYiTianDiChuangZao, "Olden·Heaven & Earth"},
            {FanZhong.GuYiDuanHongHu, "Olden·No Reds"},
            {FanZhong.GuYiQingDuanHongHu, "Olden·Clean No Reds"},
            {FanZhong.GuYiBaiWanDan, "Olden·One Million Koku"},
            {FanZhong.GuYiZhenBaiWanDan, "Olden·True One Million Koku"},
            {FanZhong.SiTongKe, "Quadruple Pung"},
            {FanZhong.YiSeSiTongke, "Pure Quadruple Pung"},
            {FanZhong.GuYiLianKaiHua, "Olden·Chain Blossom"},
            {FanZhong.GuYiSanHuaYingLu, "Olden·Flowers Dew"},
            {FanZhong.GuYiLongMenShuangYue, "Olden·Dragon Gate Leap"},
            {FanZhong.GuYiShuangLuoXuan, "Olden·Double Helix"},
            {FanZhong.GuYiYiMaDangXian, "Olden·The Leading Steed"},
            {FanZhong.GuYiWanMaBenTeng, "Olden·The Man & Steed Surge"},
            {FanZhong.GuYiLingGuiCeMa, "Olden·The Turtle & Steed Auspice"},
            {FanZhong.GuYiSheMaChengXiang, "Olden·The Snake & Steed Bliss"},
            {FanZhong.GuYiTianMaXingKong, "Olden·Heavenly Steed's Bless"},
            {FanZhong.GuYiErCiFang, "Olden·The Power of Two"},
            {FanZhong.GuYiBaiHuaQiFang, "Olden·Oddities Bloom"},
            {FanZhong.GuYiTianXiaWuShuang, "Olden·The Matchless"},
            {FanZhong.GuYiSiHaiChengShuang, "Olden·The Absolute Even"},
            {FanZhong.GuYiShenXianSuo, "Olden·Stairway to Divinity"},
            {FanZhong.GuYiSanZuDingLi, "Olden·Three Pillars of Power"},
            {FanZhong.QuanDanDui, "All Odd Pairs"},
            {FanZhong.QuanDanKe, "All Odd Triplets"},
            {FanZhong.QuanDan, "All Odds"},
            {FanZhong.QuanShuang, "All Evens"},
		};

		public static List<FanZhong> YakuIds = YakuNames.Keys.ToList<FanZhong>();
		public static Dictionary<FanZhong, int> YakuToId =
			YakuIds.Select((value, index) => new { index, value })
			.ToDictionary(pair => pair.value, pair => pair.index);

		// uses onlyIds
        public static Dictionary<string, string> AchievementNames = new Dictionary<string, string>
        {
			{"100100", "Cultivation I"},
			{"100101", "Cultivation II"},
			{"100102", "Cultivation III"},
			{"100103", "Cultivation IV"},
			{"100104", "Cultivation V"},
			{"100200", "Essentia I"},
			{"100201", "Essentia II"},
			{"100202", "Essentia III"},
			{"100203", "Essentia IV"},
			{"100204", "Essentia V"},
			{"100300", "Collector I"},
			{"100301", "Collector II"},
			{"100302", "Collector III"},
			{"100400", "Scavenger I"},
			{"100401", "Scavenger II"},
			{"100402", "Scavenger III"},
//			{"100403", "Scavenger IV"}, // Not Real?
			{"100800", "Full Devotion"},
			{"100801", "Dual Glory"},
			{"101200", "Zen·Chowbo"},
			{"101201", "Zen·Coina"},
			{"101202", "Zen·Toxtox"},
			{"101203", "Zen·Pungpon"},
			{"101204", "Zen·Cici"},
			{"101205", "Zen·Kae"},
			{"101206", "Zen·Ling"},
			{"101207", "Zen·Susy"},
			{"101208", "Zen·Abang"},
			{"101209", "Zen·Aqi"},
			{"101210", "Zen·Black"},
			{"101211", "Zen·White"},
			{"101212", "Zen·Virtue"},
			{"101213", "Zen·Sin"},
			{"101214", "Zen·Decree"},
			{"101215", "Zen·Inquiry"},
			{"101216", "Zen·Diting"},
			{"101217", "Zen·Mengpo"},
			{"101218", "Zen·Qin"},
			{"101219", "Zen·Yama"},
			{"101220", "Zen·Jizo"},
			{"101221", "Zen·Wither"},
			{"101222", "Zen·Marionette"},
			{"101223", "Zen·Nightmare"},
			{"101224", "Zen·Temptress"},
			{"101225", "Zen·Day"},
			{"101226", "Zen·Night"},
			{"101227", "Zen·Taishan"},
			{"101400", "Init·Chowbo"},
			{"101401", "Init·Coina"},
			{"101402", "Init·Toxtox"},
			{"101403", "Init·Pungpon"},
			{"101404", "Init·Cici"},
			{"101405", "Init·Kae"},
			{"101406", "Init·Ling"},
			{"101407", "Init·Susy"},
			{"101408", "Init·Abang"},
			{"101409", "Init·Aqi"},
			{"101410", "Init·Black"},
			{"101411", "Init·White"},
			{"101412", "Init·Virtue"},
			{"101413", "Init·Sin"},
			{"101414", "Init·Decree"},
			{"101415", "Init·Inquiry"},
			{"101416", "Init·Diting"},
			{"101417", "Init·Mengpo"},
			{"101418", "Init·Qin"},
			{"101419", "Init·Yama"},
			{"101420", "Init·Jizo"},
			{"101421", "Init·Wither"},
			{"101422", "Init·Marionette"},
			{"101423", "Init·Nightmare"},
			{"101424", "Init·Temptress"},
			{"101425", "Init·Day"},
			{"101426", "Init·Night"},
			{"101427", "Init·Taishan"},
			{"102500", "First Cut"},
			{"102501", "Umbral Slay"},
			{"102502", "Growling"},
			{"102503", "Haze"},
			{"102504", "Karmic Abyss"},
			{"102505", "Death Knell"},
			{"102506", "Higan Bloom"},
			{"200000", "Dig In"},
			{"200001", "King of Kongs"},
			{"200002", "Curse-Proof"},
			{"200003", "Travel Light"},
			{"200004", "Opulence"},
			{"200005", "Panoply"},
			{"200006", "Upsurge"},
			{"200007", "Boundless"},
			{"200008", "Ill-Fated"},
			{"200009", "Envenomed"},
			{"200010", "Haunted"},
			{"200011", "Impatient"},
			{"200012", "Ninefold"},
			{"200013", "Divine Wait"},
			{"200014", "Boba Victim"},
			{"200015", "Dreamlike"},
//			{"200016", ""},
			{"200017", "Gold Rush"},
			{"200018", "Fivefold Bliss"},
			{"200019", "Red Glory"},
			{"200020", "Tile Tsunami"},
			{"200021", "Billion Strike"},
			{"200022", "Kong Quest"},
			{"200023", "Gobble Up"},
			{"200024", "No Tiles Left"},
			{"200025", "314 Fan"},
			{"200026", "Fowl Play"},
			{"200027", "Whiteout"},
			{"200028", "All Black"},
			{"200029", "All Crane"},
			{"200030", "All Turtle"},
			{"200031", "All Snake"},
			{"200032", "All Demon"},
			{"200033", "Skill Spam"},
			{"200034", "Tribute King"},
			{"200035", "Endless War"},
			{"200036", "Miser"},
			{"200039", "Kong Fury"},
			{"200040", "Qi Lin's Call"},
			{"200041", "Sumptuous"},
			{"200042", "Lone Hero"},
			{"200043", "One Shot"},
			{"200044", "Billionaire"},
			{"200045", "Take The Cake"},
			{"200046", "Triple Power"},
			{"200047", "Odd Miracles"},
			{"200048", "Even Streaks"},
			{"200049", "Four Evils"},
			{"200050", "Carousel"},
			{"200051", "Cascade"},
			{"200052", "Enshrinement"},
			{"200053", "Resuscitator"},
			{"200054", "Unfaltering"},
			{"200055", "Ever-Ginseng"},
			{"200056", "Faring Well"},
			{"200057", "Intangible"},
			{"200058", "Untenable"},
			{"200059", "Treasure Trove"},
			{"200060", "Lucrative"},
			{"200061", "Dragons Unite"},
			{"200062", "Empty Handed"},
			{"200063", "Hallucination"},
			{"200064", "Demoniac"},
			{"200065", "Monkey Mayhem"},
			{"200066", "Cordillera"},
			{"200067", "Reinstated"},
			{"200068", "Eclipse"},
			{"200069", "Transcendent"},
		};

		public static List<string> AchievementIds = AchievementNames.Keys.ToList<string>();
        public static Dictionary<string, int> AchievementToId =
            AchievementIds.Select((value, index) => new { index, value })
			.ToDictionary(pair => pair.value, pair => pair.index);
    }
}
